### ISSUE TITLE
Looking Forward to the Code

### ISSUE THREAD

**Issue by GloryyrolG** [rese1f/PoseDA#1]
Thanks for your great work!

**Comment by GloryyrolG** [comment]
Hi @rese1f , may I clarify if there is no adversarial loss between the <ins>generator</ins> and <ins>lifter</ins>? Thanks,

**Comment by GloryyrolG** [comment]
Hi @rese1f , may I ask if the other part of the code will be released? Thanks.

**Comment by wenhaochai** [comment]
Sry for late reply. Yes, you are right, there is no adversarial loss between generator and lifter. In fact, the lifter is trained separately after the data is generated. As for the code, another project with GPA module may release later, and I suggest using this plug-and-play module in your own project as well.

**Comment by GloryyrolG** [comment]
Thanks for your clarification! Stay tuned:)
